### ISSUE TITLE
Feature req: CQRS / Entity Framework?

### ISSUE THREAD

**Issue by celluj34** [darcymiranda/PFire#11]
Hello;

What are your thoughts on using an ORM like Entity Framework to mediate the connection to SQLite? Obviously the `PFireDatabase` class works, but using a more fully-featured integration mechanism may help for features like code separation, transactions, database migrations, etc.

Let me know your thoughts.

Thanks,
Joe

**Comment by darcymiranda** [comment]
Agreed. When I first published this to Github 4+ years ago I didn't know anything EF or even dotnet for that matter. I've worked on projects using EF + Sqlite in the past, so it should work no problem. Feel free to create a PR to use EF instead, and I'd gladly accept it! 

The pattern used right now merges the responsibilities of the data and handler together in the same class. Not exactly ideal, but it's fine, in my opinion. The data model can't change since we're tied to the XFire client. If I were to start this from scratch again, I'd definitely follow CQRS just for easy of use/similarity purposes. I personally don't think it's worth doing at the moment.

**Comment by TheLogster** [comment]
EF under dotnet core is a pain.

My vote is to stick to SQLite and use Dapper as the ORM layer.

Dapper works with SQLServer as SQLite, and offers good performance.

**Comment by ivom2k** [comment]
My vote goes to Entity Framework Core. Stick to the standards.

**Comment by celluj34** [comment]
Guys, I got some really neat stuff cooking for this one. I think you're going to like it... I just need to get some of the kinks worked out and write some tests.

**Comment by oveldman** [comment]
At the moment, the EF is now merged in the master branche. Can this topic to be closed, or is this topic still open for reporting bugs? I prefere to open another topic for the specific bug about EF if the bug appear.
